### ISSUE TITLE
ansible skipping execution 

### ISSUE THREAD

**Issue by aditya9366** [alexdzyoba/redis-packer#1]
Hi , 
I used your code for testing out the ansible provisioner that you used it seems like it is also skipping the ansible execution just like my code as it shows no host present , i am able to use ansible-local but i wanted to use the ansible remote provisioner to be able to show the capacity of ansible via packer . 
Can you please see if its working for you or is it showing skipping host ??

**Comment by dzeban** [comment]
Packer and Ansible have some interoperability issues now - ansible remote provisioner doesn't work out of the box with docker builder. There is a workaround though - https://github.com/hashicorp/packer/issues/3260#issuecomment-199233230

Please, try this.
